# Generated by Django 6.0.7 on 2026-09-03 14:55

import lrb.core.utilis.files
import lrb.core.validators.phone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('logo_light', models.ImageField(blank=True, null=True, upload_to=lrb.core.utilis.files.company_logo_light_upload_path)),
                ('logo_dark', models.ImageField(blank=True, null=True, upload_to=lrb.core.utilis.files.company_logo_dark_upload_path)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, validators=[lrb.core.validators.phone.validate_phone_number])),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
