# Generated by Django 6.0.7 on 2026-09-03 14:55

import django.db.models.deletion
import django.utils.timezone
import lrb.accounts.managers
import lrb.core.utilis.files
import lrb.core.validators.phone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('is_email_verified', models.BooleanField(default=False, help_text='Whether the user has confirmed ownership of their email address.')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Last Name')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[lrb.core.validators.phone.validate_phone_number], verbose_name='Phone Number')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=lrb.core.utilis.files.avatar_upload_path)),
                ('is_founder', models.BooleanField(default=False, help_text='The user who originally registered the company. Founders cannot be deactivated, locked, deleted, or demoted from ownership by anyone, including other owners.')),
                ('can_login', models.BooleanField(default=True, help_text='Determines whether the user can sign in')),
                ('password_reset_required', models.BooleanField(default=False)),
                ('last_password_change', models.DateTimeField(blank=True, null=True)),
                ('failed_login_attempts', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='company.company')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company'], name='accounts_us_company_7b39c2_idx'), models.Index(fields=['is_active'], name='accounts_us_is_acti_a5841d_idx'), models.Index(fields=['can_login'], name='accounts_us_can_log_1a6d4f_idx')],
            },
            managers=[
                ('objects', lrb.accounts.managers.UserManager()),
            ],
        ),
    ]
